name: Deploy S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION>  # Replace with your AWS region

      - name: Change to Pulumi project directory
        run: ./

      - name: Preview Changes
        run: pulumi preview

      - name: Deploy Changes
        run: pulumi up --yes
