name: Deploy S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Pulumi Access Token
        run: pulumi login --cloud-url "https://api.pulumi.com/" --cloud-access-token "${{ secrets.PULUMI_ACCESS_TOKEN }}"

      - name: Change to Pulumi project directory
        run: cd infra

      - name: Preview Changes
        run: pulumi preview

      - name: Deploy Changes
        run: pulumi up --yes
